[versions]
kotlin = "2.1.10"
androidApplicationPlugin = "8.8.2"
materialThemeBuilder = "1.5.1"
ksp = "2.1.10-1.0.31"
autoresconfig = "1.2.2"
gson = "2.12.1"
guava = "33.4.0-jre"
glide = "4.16.0"
appcenterAnalytics = "5.0.6"
appcenterCrashes = "5.0.6"
xposedApi = "82"
dexkit = "2.0.3"
appcompat = "1.7.0"
preferenceKtx = "1.2.1"
constraintLayout = "2.2.1"
recyclerviewSelection = "1.1.0"
room = "2.6.1"
lifecycleLiveDataKtx = "2.8.7"
fragmentKtx = "1.8.6"
material = "1.12.0"
about = "2.5.2"
fastscroll = "1.3.0"
rikkaMaterial = "2.7.2"
rikkaMaterialPreference = "2.0.0"

[libraries]
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
xposedApi = { module = "de.robv.android.xposed:api", version.ref = "xposedApi" }
dexkit = { module = "org.luckypray:dexkit", version.ref = "dexkit" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
preferenceKtx = { module = "androidx.preference:preference-ktx", version.ref = "preferenceKtx" }
constraintLayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintLayout" }
recyclerviewSelection = { module = "androidx.recyclerview:recyclerview-selection", version.ref = "recyclerviewSelection" }
roomRuntime = { module = "androidx.room:room-runtime", version.ref = "room" }
roomCompiler = { module = "androidx.room:room-compiler", version.ref = "room" }
roomKtx = { module = "androidx.room:room-ktx", version.ref = "room" }
lifecycleLiveDataKtx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycleLiveDataKtx" }
fragmentKtx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragmentKtx" }
material = { module = "com.google.android.material:material", version.ref = "material" }
about = { module = "com.drakeet.about:about", version.ref = "about" }
fastscroll = { module = "me.zhanghai.android.fastscroll:library", version.ref = "fastscroll" }
rikkaMaterial = { module = "dev.rikka.rikkax.material:material", version.ref = "rikkaMaterial" }
rikkaMaterialPreference = { module = "dev.rikka.rikkax.material:material-preference", version.ref = "rikkaMaterialPreference" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
glideCompiler = { module = "com.github.bumptech.glide:compiler", version.ref = "glide" }
appcenterAnalytics = { module = "com.microsoft.appcenter:appcenter-analytics", version.ref = "appcenterAnalytics" }
appcenterCrashes = { module = "com.microsoft.appcenter:appcenter-crashes", version.ref = "appcenterCrashes" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "androidApplicationPlugin" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
materialThemeBuilder = { id = "dev.rikka.tools.materialthemebuilder", version.ref = "materialThemeBuilder" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
autoresconfig = { id = "dev.rikka.tools.autoresconfig", version.ref = "autoresconfig" }
